SpecificProcess:
  AndroidRuntime: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}(\s)*\d{4,5}(\s)*\d{4,5}(\s)*[a-zA-Z]\sAndroidRuntime:.*'
  HomeApp: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}\s\d{4,5}\s\d{4,5}\s[a-zA-Z]\sHomeApp([a-zA-Z]|(\|))*:.*'
  ActivityThread&chatty: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}(\s)*\d{4,5}(\s)*\d{4,5}\s[a-zA-Z]\s(ActivityThread|chatty)(\s)*:.*'
IssuesGeneralFields:
  Number: null
  Details: null
  Timestamp: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}'
  LogLevel: '(?m)^(?:0[1-9]|1[0-2])-(?:0[1-9]|(?:1|2)[0-9]|3(?:0|1))\s(?:(?:(?:0|1)[0-9])|(?:2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}(?:\s)*\d{4,5}(?:\s)*\d{4,5}\s([a-zA-Z])\s.*'
  OtherFields:
    #otherField1: '(?m)^(?:0[1-9]|1[0-2])-(?:0[1-9]|(?:1|2)[0-9]|3(?:0|1))\s(?:(?:(?:0|1)[0-9])|(?:2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}(?:\s)*\d{4,5}(?:\s)*\d{4,5}\s([a-zA-Z])\s.*'
Issues:
  Crashes:
    specific_process:
      AndroidRuntime: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}(\s)*\d{4,5}(\s)*\d{4,5}\s[a-zA-Z]\sAndroidRuntime:.*'
    regex: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}(\s)*\d{4,5}(\s)*\d{4,5}(\s)*[a-zA-Z]\sAndroidRuntime:\sFATAL\sEXCEPTION.*'
    detailing_mode: raw
    grouping: null
    additional_fields:
  rpc:
    specific_process:
      HomeApp: '(?m)^(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3(0|1))\s(((0|1)[0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}\s\d{4,5}\s\d{4,5}\s[a-zA-Z]\sHomeApp([a-zA-Z]|(\|))*:.*'
    regex: '(?m)^(?:0[1-9]|1[0-2])-(?:0[1-9]|(?:1|2)[0-9]|3(?:0|1))\s(?:(?:(?:0|1)[0-9])|(?:2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}\s\d{4,5}\s\d{4,5}\s[a-zA-Z]\sHomeApp(?:[a-zA-Z]|\.|\d|\s|:|(?:\|))*\/(?P<name>[a-zA-Z]*):\s*(?:[a-zA-Z]*).*code=(?P<status_code>[a-zA-Z]*).*cause=(?P<cause>(?:[a-zA-Z]|:|\s|_)*).*'
    detailing_mode: group
    grouping: '(?m)^(?:0[1-9]|1[0-2])-(?:0[1-9]|(?:1|2)[0-9]|3(?:0|1))\s(?:(?:(?:0|1)[0-9])|(?:2[0-3])):[0-5][0-9]:[0-5][0-9]\.\d{3}\s\d{4,5}\s\d{4,5}\s[a-zA-Z]\sHomeApp(?:[a-zA-Z]|\.|\d|\s|:|(?:\|))*\/(?P<name>[a-zA-Z]*):\s*(?:[a-zA-Z]*).*code=(?P<status_code>[a-zA-Z]*).*cause=(?P<cause>(?:[a-zA-Z]|:|\s|_)*).*'
    additional_fields:
Priority:
  rpc: 100
  Crashes: 2
